apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "upgradeResponder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
    helm.sh/chart: {{ include "upgradeResponder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/upgradeResponderConfigMap: {{ include (print $.Template.BasePath "/upgradeResponderConfigMap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "upgradeResponder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: APPLICATION_NAME
            value: {{ .Values.applicationName }}
          - name: INFLUXDB_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBUrl
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBUser
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name }}
                key: influxDBPassword
          - name: PORT
            value: "{{ .Values.service.port }}"
          - name: CACHE_SYNC_INTERVAL
            value: "{{ .Values.flags.cacheSyncInterval }}"
          - name: CACHE_SIZE
            value: "{{ .Values.flags.cacheSize }}"
          {{- if .Values.flags.scarfEndpoint }}
          - name: SCARF_ENDPOINT
            value: "{{ .Values.flags.scarfEndpoint }}"
          {{- end }}
          - name: SCARF_TIMEOUT
            value: "{{ .Values.flags.scarfTimeout }}"
          command:
          - upgrade-responder
          args:
          - --debug
          - start
          - --application-name
          - $(APPLICATION_NAME)
          - --upgrade-response-config
          - /run/secrets/response-config.json
          - --request-schema
          - /run/secrets/request-schema.json
          - --influxdb-url
          - $(INFLUXDB_URL)
          - --influxdb-user
          - $(INFLUXDB_USER)
          - --influxdb-pass
          - $(INFLUXDB_PASSWORD)
          - --port
          - $(PORT)
          - --cache-sync-interval
          - $(CACHE_SYNC_INTERVAL)
          - --cache-size
          - $(CACHE_SIZE)
          {{- if .Values.flags.scarfEndpoint }}
          - --scarf-endpoint
          - $(SCARF_ENDPOINT)
          {{- end }}
          - --scarf-timeout
          - $(SCARF_TIMEOUT)
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - mountPath: /run/secrets/response-config.json
            name: {{ include "upgradeResponder.upgradeResponderConfigMapName" . }}
            subPath: response-config.json
          - mountPath: /run/secrets/request-schema.json
            name: {{ include "upgradeResponder.upgradeResponderConfigMapName" . }}
            subPath: request-schema.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ include "upgradeResponder.upgradeResponderConfigMapName" . }}
        configMap:
          name: {{ include "upgradeResponder.upgradeResponderConfigMapName" . }}
